package com.yorren.moviecatalogue.utils;

import com.yorren.moviecatalogue.data.Movies;
import com.yorren.moviecatalogue.data.TvShows;

import java.util.ArrayList;
import java.util.List;

public class DataDummy {
    public static ArrayList<Movies> generateDummyMovies() {
        ArrayList<Movies> movies = new ArrayList<>();

        movies.add(new Movies("m1 ",
                "My Hero Academia: Heroes Rising",
                "Kenji Nagasaki, Kohei Horikoshi",
                "Animation, Action, Superheroes",
                "26 February 2020",
                "1h 44min",
                "The League of Villains is pursued by Endeavor and Hawks, while driving off in a truck carrying mysterious cargo. The heroes destroy the truck, but fail to apprehend the League members, and find an empty life support capsule inside. The man inside, a villain named Nine, has escaped and regroups with his team of villains, planning to create a society where those with strong Quirks rule over others.\n" +
                        "\n" +
                        "U.A. High's Class 1-A has been sent to the remote Nabu Island as part of a safety program. Izuku Midoriya, the holder of One for All, meets Mahoro Shimano, and her brother Katsuma, residents of the island. Bonding with them along with his rival Katsuki Bakugo, they discover that Katsuma wishes to become a hero, but Mahoro seeks to dissuade him.\n" +
                        "\n" +
                        "Meanwhile, Mahoro and Katsuma's father is attacked by Nine and his party, with Nine stealing his Quirk. Nine, who has been empowered by All For One, can steal and possess up to nine Quirks, but his body cannot handle these Quirks without suffering damage. He seeks to use the stolen Quirk to heal himself, becoming near-invincible, but it is incompatible with his blood type. Nine surmises that the man's children might possess a better variant of it, and pursues them.\n" +
                        "\n" +
                        "Nine and his gang arrive on the island and destroy all means of escape and communication. Class 1-A learns of the invasion and split up to stop the villains and protect the island residents. Nine finds the children and confirms Katsuma possesses the Quirk he seeks, but Midoriya intervenes before he can steal it; however, neither he nor Bakugo are a match against Nine. Despite this, they force him to retreat due to overusing his Quirks.\n" +
                        "\n" +
                        "Class 1-A regroups and decide to attack the villains head-on, while awaiting the arrival of other heroes. Upon evacuating the islanders, the class manage to defeat the rest of Nine's crew, but are incapacitated by Nine, except for Midoriya and Bakugo. Seeing no other way to defeat Nine, Midoriya transfers One For All into Bakugo, while he uses its leftover embers. Together, the two defeat Nine, but Midoriya's One For All seemingly fades afterwards.\n" +
                        "\n" +
                        "As professional heroes arrive, All Might finds an unconscious Bakugo and Midoriya. He realizes that One For All remains within Midoriya, as the transfer into Bakugo was interrupted, theorizing that the previous wielders of One For All wish for Midoriya to keep it. Elsewhere, Tomura Shigaraki finds and kills the weakened Nine out of spite.\n" +
                        "\n" +
                        "With Nine's gang apprehended, the class repair damage to the island before returning home. Midoriya and Bakugo, who has lost memory of wielding One For All, say goodbye to Katsuma and Mahoro. The movie ends as Midoriya assures Katsuma he can become a hero, as All Might had done for him previously.",
                "https://musicart.xboxlive.com/7/24805100-0000-0000-0000-000000000002/504/image.jpg"));

        movies.add(new Movies("m2 ",
                "My Hero Academia: Two Heroes",
                "Kenji Nagasaki, Kohei Horikoshi",
                "Animation, Action, Superheroes",
                "26 March 2019",
                "1h 37min",
                "A flashback shows a young All Might in Las Vegas, dealing with a couple of villains that robbed a casino, aided by his friend David who has worked with All Might and designed many of his suits.\n" +
                        "\n" +
                        "Going back to the present, All Might brings Midoriya with him to a moving floating city island called \"I Island\" for a convention that is currently happening there. Upon arriving, All Might and Midoriya are greeted by David's daughter Melissa, who welcomes the two and takes them to David.\n" +
                        "\n" +
                        "After the reunion, All Might runs tests with David, during which he realizes that All Might's Quirk is nearly depleted. He is horrified, believing that All Might will not be able to keep his role as the Symbol of Peace. Meanwhile, Melissa shows Midoriya around the island, and they run into Midoriya's classmates from class 1-A, who were invited to the island for various reasons. After enjoying the island's events, Melissa invites class 1-A to join a formal party being held with all heroes present. Before the party, Melissa gives Midoriya a gauntlet that allows him to use his Quirk fully without getting hurt.\n" +
                        "\n" +
                        "Meanwhile, Wolfram, a villain who had secretly arrived on the island, took control of the island's security system during the party and threatens to kill its residents. He restrains all of the pro-heroes attending, including All Might, and takes David and his assistant Sam hostage in order to break into the island's vault. Midoriya, Melissa, and the rest of class 1-A managed to evade the attackers. They decide to fight the villains and free the heroes, by reaching the top of the building and deactivating the security system. Wolfram deploys forces to stop them, but Midoriya and Melissa manage to climb to the top regardless.\n" +
                        "\n" +
                        "At the top of the tower, they discover that David and Sam orchestrated the night's events with actors. Their goal was to steal back their greatest invention - a headset that maximizes the power of a person's Quirk, which had been locked away to prevent it from falling into the wrong hands. David wishes to give it to All Might, so that he could maintain his role as a hero. However, Wolfram arrives and reveals that he is not an actor, but a real villain working with Sam to retrieve the headset for himself. Wolfram steals the headset and attempts to kill Sam and Melissa, but David and Midoriya save them.\n" +
                        "\n" +
                        "Wolfram holds off Midoriya, kidnaps David, and escapes to the rooftop. Midoriya fails to prevent Wolfram from taking off in a helicopter with David, but Melissa takes control of the security system and frees the pro heroes. All Might reaches the roof and stops the helicopter from taking off.\n" +
                        "\n" +
                        "Wolfram then uses the headset to amplify his power, creating a giant metal body with David trapped inside. He overpowers All Might, revealing that he is secretly in league with All Might's nemesis All For One, who gave Wolfram additional Quirks and orchestrated the night's events to demoralize All Might. Lacking the strength to defeat Wolfram alone, All Might asks for Midoriya's aid. The rest of the students soon arrive on the roof and help All Might and Midoriya, who combine their power to defeat Wolfram, freeing David.\n" +
                        "\n" +
                        "As the sun rises, David and All Might reflect on how Melissa and Midoriya are the next generation of heroes and how the world will be in good hands even after All Might's Quirk is gone.",
                "https://cdn.myanimelist.net/images/anime/1994/111685l.jpg"));

        movies.add(new Movies("m3 ",
                "Anohana: The Flower We Saw That Day",
                "Tatsuyuki Nagai",
                "Animation, Romance, Drama, Slice of Life",
                "31 August 2013",
                "1h 39min",
                "In Chichibu, Saitama, a group of six sixth-grade-age[2] childhood friends drift apart after one of them, Meiko \"Menma\" Honma, dies in an accident. Five years[3] after the incident, the leader of the group, Jinta Yadomi, has withdrawn from society, does not attend high school,[4] and lives as a recluse. One summer day, the ghost of an older-looking Menma appears beside him and asks to have a wish granted, reasoning that she cannot pass on into the afterlife until it is fulfilled. At first, he only tries to help her minimally because he thinks he is hallucinating. But since Menma does not remember what her wish is, Jinta gathers his estranged friends together once again, believing that they are the key to solving this problem. All of the group joins him, though most of them do so reluctantly. However, things grow increasingly complicated when his friends accuse him of not being able to get over Menma's death, as they cannot see her and believe Jinta is hallucinating. Menma shows her presence to the group in order to prove that she is indeed real. All the group members eventually wish to shoulder the blame for Menma's death and long-hidden feelings among the group are rekindled. The group struggles as they grow from trying to help Menma move on and help each other move on as well.",
                "https://m.media-amazon.com/images/M/MV5BNTc1NzEwOTU0MV5BMl5BanBnXkFtZTgwNTMxMzY5MDE@._V1_.jpg"));

        movies.add(new Movies("m4 ",
                "Kimetsu no Yaiba the Movie: Mugen Train",
                "Haruo Sotozaki",
                "Animation, Adventure, Fantasy, Historical Drama",
                "16 October 2020",
                "1h 57min",
                "Tanjiro Kamado, his demon sister Nezuko, Zenitsu Agatsuma, and Inosuke Hashibira board a train[N 1] to assist the Flame Hashira Kyōjurō Rengoku in his mission to hunt for a demon that has killed many demon slayers, along with Tanjiro wanting to learn the secrets of his Fire Breathing technique derived from his father's Hinokami Kagura. Though Kyōjurō cannot provide any answers to the latter, he invites Tanjiro to serve as his apprentice. Tanjiro, Zenitsu, and Inosuke agree to be Kyōjurō's apprentices after watching him kill two demons aboard the train. Soon they, along with many passengers inside the car, fall into a deep sleep. Enmu, Lower Rank One of the Twelve Kizuki and the source of the sleep enchantment, instructs four children passengers, all suffering from severe insomnia, to enter the demon slayers' dreams and destroy their spiritual cores so that they can't wake up again. In exchange, Enmu will allow them a peaceful sleep.\n" +
                        "\n" +
                        "During their sleep, Tanjiro and his companions have happy dreams. Tanjiro in particular dreams of an alternate reality in which his family was never slain by a demon and Nezuko is still human. After the real Nezuko attempts to awaken Tanjiro with her Blood Demon Art, he realizes that he is dreaming and leaves his family. Still unable to wake up, a vision of his father instructs him to kill himself in the dream, which he manages to do by cutting his own neck. At the same time, Nezuko uses her power to sever the intruders' connections and awaken the passengers. In fear of Enmu, they attack Tanjiro, who knocks them out.\n" +
                        "\n" +
                        "While Nezuko awakens the others, Tanjiro confronts Enmu, who attempts to hypnotize him with his Blood Demon Art, though Tanjiro quickly and repeatedly awakens himself by cutting himself in the dream. When Enmu's next induced dream depicts Tanjiro's family expressing their hatred for him for letting them die at the demon's hand, an enraged Tanjiro manages to decapitate Enmu. However, Enmu does not die, and reveals that he fused his head with the train, causing the train and its cars to become covered in flesh that Enmu can control. Kyōjurō instructs Inosuke and Tanjiro to look for Enmu's neck while he, Nezuko, and Zenitsu stay behind to protect the other passengers. Tanjiro and Inosuke reach the engine and discover Enmu's neckbone, though Tanjiro is stabbed in the abdomen by the engineer under Enmu's influence. With Inosuke's assistance and with Tanjiro continuing to resist Enmu's hypnosis, Tanjiro severs the neckbone with his Fire Breathing, killing Enmu and causing the train to derail and crash. Despite several injured, there are no casualties among any of the passengers. Kyōjurō helps Tanjiro use his breathing techniques to close the wound, but advises him to settle down to prevent him from re-opening the wound and dying.\n" +
                        "\n" +
                        "Akaza, the Upper Rank Three of the Twelve Kizuki, appears soon after and attacks the demon slayers while also attempting to persuade Kyōjurō into renouncing his humanity and becoming a demon, which Kyōjurō continually refuses, much to Akaza's anger and bewilderment. Kyōjurō fights Akaza alone with neither Tanjiro nor Inosuke able to help without hindering Kyōjurō. After Kyōjurō suffers several injuries throughout the battle, Akaza fatally impales him through the stomach with his arm. Despite the fatal blow, Kyōjurō holds Akaza down to be killed by sunlight as morning begins to break. Akaza tears his limbs off to free himself and flees into the shade of the nearby woods. Tanjiro chases after him and impales him with his sword, though Akaza still mananges to escape, taking Tanjiro's sword. Tanjiro angrily calls him a coward for running away and declares Kyōjurō the winner of the fight.\n" +
                        "\n" +
                        "Kyōjurō requests Tanjiro share some final words with his younger brother and to search for records written by the previous Flame Hashira, Kyōjurō's father, to aid him in his quest. After experiencing a vision of his deceased mother, who expresses pride in her son, Kyōjurō succumbs to his injuries. The Hashira and Demon Slayer Corps are informed of Kyōjurō's death, while Tanjiro and the others mourn him.",
                "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/e/eb/Mugen_Train_Poster_1.jpeg"));

        movies.add(new Movies("m5",
                "Weathering with You",
                "Makoto Shinkai",
                "Animation, Fantasy, Romance",
                "19 July 2019",
                "1h 52min",
                "In June 2021, first year high schooler Hodaka Morishima escapes Kōzu-shima in order to get away from his troubled home life to Tokyo. When his ferry to the city is hit by a rainstorm, he is saved by Keisuke Suga, who gives Hodaka his business card. As Hodaka becomes broke and struggles to find work, he meets Hina Amano, an employee of a McDonald's restaurant. She takes pity on him and gives him food. Later on, Hodaka finds an abandoned Makarov PM handgun in a waste bin he fell onto. After arriving at Suga's business location, he meets him there and his niece, Natsumi. Suga hires him as his assistant at a small occult magazine publishing company, where they investigate urban legends related to the unusually rainy weather in Tokyo. From a psychic, they hear the legend of a \"sunshine girl\" who can control the weather.\n" +
                        "\n" +
                        "Hodaka sees Hina being intimidated into working at a back-alley club. After a brief chase, he scares off the club owners by firing his gun into the air, thinking it was a toy. He and Hina escape; she takes him to Yoyogi Kaikan, an abandoned building with a shrine on the roof, where he throws the gun away. Hina astonishes Hodaka by demonstrating her ability to clear the sky by praying. Hodaka finds out that Hina lives alone with her brother Nagi, and they have no adult guardian. Seeing how they are in a financial trouble, Hodaka proposes to start a business with Hina with the ability of sunshine girl: a job to clear the weather for events such as weddings and parties. They create a website to accept orders and their business quickly becomes a success. However, when clearing the sky for the Jingu Fireworks Festival, Hina is shown on television and their site gets flooded with requests, so they decide to close their business.\n" +
                        "\n" +
                        "A detective with the police search for Hodaka, as his family filed a missing person report. They find out that Hodaka was caught using the gun on a security camera. Officers arrive at the apartment where Hina lives with Nagi and interrogate her while Hodaka hides; Hina realizes that because they have no legal guardians, with their mother having died recently, social services are going to take them into custody and separate them. Right after the police leave, Suga visits Hodaka, having also been visited by the police. Suga fires Hodaka and gives him his separation pay, explaining that the police suspect him of kidnapping Hodaka. Hodaka, Hina and Nagi try to run away, but they are halted by the worsening weather. They take shelter in a hotel, and spend the night with instant food and doing karaoke. As midnight passes, Hina reveals that her body is slowly turning into water the more she uses her power. She explains that she is the cause of the abnormal weather and is intended to be a human sacrifice, and her disappearance will return the weather to normal. Hodaka promises to protect her, but the next morning, Hina has vanished into the sky and the rain has stopped.\n" +
                        "\n" +
                        "In the morning, the police track Hodaka to the hotel room. Nagi is sent to the children's counseling center and Hodaka is taken to the police station. Having already fallen in love with Hina, Hodaka decides to bring her back to Earth and escapes from the police custody with the help of Natsumi and her Honda Super Cub. After her motorcycle is immobilized, Hodaka resumes on-foot to Yoyogi Kaikan building to reach the shrine. Inside, he encounters Suga, who attempts to stop him. The police surround Hodaka, but Suga, now inspired by Hodaka's desperation to see Hina, helps him escape. At the roof-top shrine, Hodaka jumps through the shrine gate and is transported into the sky, where he finds Hina and asks her to leave with him, insisting that Hina let go of her worries about the weather and start living for herself. As soon as they come back to the rooftop shrine, Hina, Hodaka, Natsumi, Nagi, and Suga are all arrested, and the heavy rains resume. Hodaka is sentenced to a three-year probation and sent back to his home in Kōzu-shima.\n" +
                        "\n" +
                        "Three years later, the rain has been falling without end in Tokyo, submerging much of the city. In the spring of 2024, having finished his probation, Hodaka graduates from high school and returns to Tokyo to start college. He meets with Suga, who has expanded his business. After Suga encourages him to find Hina, Hodaka finds her praying on a street overlooking the drowned city. They reunite, with Hodaka promising her that they will be alright.",
                "https://m.media-amazon.com/images/M/MV5BNzE4ZDEzOGUtYWFjNC00ODczLTljOGQtZGNjNzhjNjdjNjgzXkEyXkFqcGdeQXVyNzE5ODMwNzI@._V1_.jpg"));

        movies.add(new Movies("m6 ",
                "A Silent Voice",
                "Naoko Yamada",
                "Animation, Teen, Psychological Drama",
                "17 September 2016",
                "2h 10min",
                "Japanese high school student Shoya Ishida intends to kill himself when he changes his mind at the last minute and decides to wrap up a loose end. It is revealed that in sixth grade a new student named Shoko Nishimiya joins Shoya's class and is revealed to be deaf. She tries to integrate with the class but ends up being an easy target for Shoya and his friends to bully. When word of the bullying reaches the principal, Shoya is singled out as the culprit by his teacher resulting in the class's bullying becoming directed toward him. Shoya blames Shoko, and the two get into a physical altercation. Shoko is subsequently transferred to another school and Shoya later finds a notebook Shoko left behind and keeps it.\n" +
                        "\n" +
                        "Being outcasted throughout middle school for his reputation as a bully, Shoya, now in highschool is a depressed loner who is unable to look others in the eyes and envisions a \"X\" mark over people's faces. To wrap up his loose end, Shoya goes to return Shoko's notebook at the sign language center and apologize but panics and asks to be friends instead. Shoko accepts his offer, leading Shoya to endeavor to make up for his bullying of Shoko. Tomohiro Nagatsuka, another loner, also befriends Shoya after he helps him out with a bully.\n" +
                        "\n" +
                        "One day, Shoya accidentally drops Shoko's notebook into a river, he then jumps in to retrieve it, which is prohibited. Yuzuru, Shoko's younger sister, takes a photo of Shoya jumping in and posts it online to get revenge on him, eventually leading to Shoya getting suspended. Shoya finds Yuzuru, who ran away from home, and brings her to stay at his house. When she leaves in the middle of the night, Shoya follows and the two of them make up with each other and become friends.\n" +
                        "\n" +
                        "Shoya and Shoko reunite with Miyoko Sahara, a classmate from elementary school who was friendly to Shoko. Shoko later gives Shoya a gift and confesses her feelings for him, but because she tries to speak her affections rather than signing them out, Shoya mishears her.\n" +
                        "\n" +
                        "Shoya invites Shoko to an amusement park with Tomohiro, Miyoko, Miki Kawai (another classmate from elementary school) and Satoshi Mashiba (Miki's friend). There, they joined by another classmate from elementary school, Naoka Ueno, who drags Shoko into a ferris wheel. Naoka voices her feelings of hatred for Shoko, blaming her for creating a rift between her and Shoya, whom she is infatuated with. Yuzuru, who had been secretly recording the encounter, shows the video of this to Shoya. Desperate to remain blameless for her part in bullying Shoko following the leak, Miki exposes Shoya's past to the students who were oblivious to it. Later, she attempts to apologize to the group, but Shoya blows everyone off after Naoka remains dismissive.\n" +
                        "\n" +
                        "Shoya learns Shoko and Yuzuru's grandmother has died recently. To cheer them up, Shoya takes them to the countryside and sees that Shoko blames herself for everything that has happened to him. Shoya decides to devote his entire social life to the sisters.\n" +
                        "\n" +
                        "During a fireworks festival, Shoko goes home under the guise of finishing homework. Shoya follows when Yuzuru asks him to get her camera. When he arrives, he finds Shoko standing on the balcony, about to commit suicide. Shoya succeeds in grabbing her and pulls her back up, but falls into the river below. He is rescued by his former best friends in elementary school but slips into a coma. Hoping to help Shoya, Shoko meets with each of the group members to explain her and Shoya's situations.\n" +
                        "\n" +
                        "One night, Shoko dreams about receiving a farewell visit from Shoya. Horrified, she runs to the bridge and collapses in tears. Shoya, awakening from his coma, stumbles to the bridge and finds her there. He apologizes for the way he treated her, asking her to stop blaming herself and admits that, while he once considered ending his own life, he has since decided against it. Shoya then asks her to help him continue to live to which she agrees.\n" +
                        "\n" +
                        "When Shoya returns to school he is reunited with his friend and after coming to understand how much his new friends still care for him, they reconcile. The friends go to the school festival together and Shoya finds he is finally able to look at other people's faces again as the envisions the \"X\" marks falling away. Looking around at his family and all the new friends he has made, Shoya starts tearing up knowing he has finally redeemed himself.",
                "https://assets.mycast.io/posters/a-silent-voice-koe-no-katachi-fan-casting-poster-2263-large.jpg"));

        movies.add(new Movies("m7 ",
                "Your Name",
                "Makoto Shinkai",
                "Animation, Romance, Fantasy",
                "26 August 2016",
                "1h 47min",
                "Mitsuha Miyamizu is a high school girl living in the rural town of Itomori near Hida. Bored of the town, she wishes to be a Tokyo boy in her next life. She inexplicably begins to switch bodies intermittently with Taki Tachibana, a high school boy in Tokyo, waking up as the other person and having to live through their activities and social interactions for the day. The two initially believe these experiences to be vivid dreams, but eventually realize they can communicate with each other by leaving messages on paper, phones and sometimes on each other's skin. Mitsuha (in Taki's body) sets Taki up on a date with his coworker Miki Okudera, while Taki (in Mitsuha's body) causes Mitsuha to become popular at school. One day, Taki (in Mitsuha's body) accompanies Mitsuha's grandmother Hitoha and her sister Yotsuha to leave the ritual alcohol kuchikamizake, made by the sisters, as an offering at the Shinto shrine located on a mountaintop outside the town. It is believed to represent the body of the village guardian god ruling over human connections and time. Taki reads a note from Mitsuha about the comet Tiamat, expected to pass nearest to Earth on the day of the autumn festival. The next day, Taki wakes up in his body and goes on a date with Miki, who tells him she enjoyed the date but also that she can tell that he is preoccupied with thoughts of someone else. Taki attempts to call Mitsuha on the phone, but cannot reach her and finds the body-switching has ended.\n" +
                        "\n" +
                        "Taki, Miki, and their friend Tsukasa travel to Gifu by train on a trip to Hida, though Taki does not know the name of the town, instead relying on sketches he has made of the surrounding landscape from memory. A restaurant owner in Hida recognizes the town in the sketch as Itomori, being originally from there. He takes Taki and his friends to the ruins of the town, which has been destroyed and where five hundred residents were killed when the comet Tiamat unexpectedly fragmented three years earlier. While gazing over the impact crater in disbelief, Taki observes Mitsuha's messages disappear from his phone and his memories of her begin to gradually fade. Taki finds Mitsuha's name in the record of fatalities, and he wonders if the body-switching was just a dream. While Miki and Tsukasa return to Tokyo, Taki journeys to the shrine, hoping to reconnect with Mitsuha and warn her about the comet. In the shrine, Taki drinks Mitsuha's kuchikamizake then lapses into a vision, where he glimpses Mitsuha's past. He also recalls that he had already encountered Mitsuha on a train three years earlier when she came to Tokyo in her own timeframe to find him, though Taki did not recognize her as the body-switching was yet to occur in his timeframe. Before leaving the train in embarrassment, Mitsuha had handed him her hair ribbon, which he has since worn on his wrist as a good-luck charm.\n" +
                        "\n" +
                        "Taki wakes up in Mitsuha's body at her house on the morning of the festival. Hitoha deduces what has happened and tells him the body-switching ability has passed down in her family as caretakers of the shrine. Taki convinces Tessie and Sayaka, two of Mitsuha's friends, to get the townspeople to evacuate Itomori, by disabling the electrical substation and broadcasting a false emergency alert. Taki heads to the shrine, realizing that Mitsuha must be in his body there, while Mitsuha wakes up in Taki's body. At the mountaintop during sunset, the two sense each other's presence, but are separated due to contrasting timeframes and cannot see each other. When twilight falls (referred to in the film as \"magic hour\" or kataware-doki),[note 1] they return to their own bodies and see each other in person. After Taki returns Mitsuha's ribbon, they attempt to write their names on each other's palm so that they will remember each other. Before Mitsuha can write hers, however, twilight passes and they revert to their respective timeframes. When the evacuation plan fails, Mitsuha has to convince her father Toshiki, the mayor of Itomori, to evacuate everyone. Before doing so, Mitsuha notices her memories of Taki are fading away and discovers he wrote \"I love you\" on her hand instead of his own name. The comet's fragments crash to Earth and destroy Itomori. Taki wakes up in his own timeframe remembering nothing.\n" +
                        "\n" +
                        "Five years later, Taki has graduated from university and searches for a job. He senses that he lost something important that he cannot identify, and feels inexplicable interest in the events surrounding the comet, now eight years past. The town of Itomori had been destroyed; however, all of its people survived as they had evacuated just in time. Meanwhile, Mitsuha has since moved to Tokyo. Some time later, Taki and Mitsuha glimpse each other when their respective trains pass each other, and they are instantly drawn to seek one another. Each disembarks and races to find the other, finally meeting at the stairs of Suga Shrine [ja]. Taki calls out to Mitsuha, saying that he feels that he knows her, and she responds likewise. Having found what each had long searched for, they shed tears of happiness and simultaneously ask each other for their name.",
                "https://images-na.ssl-images-amazon.com/images/I/517vpKwzcpL.jpg"));

        movies.add(new Movies("m8 ",
                "5 Centimeters per Second",
                "Makoto Shinkai",
                "Animation, Romance, Drama",
                "3 March 2007",
                "1h 5min",
                "In 1991, Takaki Tōno quickly befriends Akari Shinohara after she transfers to his elementary school in Tokyo. They grow very close to each other due to similar interests and attitudes such as both preferring to stay inside during recess due to their seasonal allergies. As a result, they form a strong bond which is shown when they speak to each other using their given names without any form of honorifics as that is a sign of deep friendship and familiarity in Japan.Right after graduating from elementary school in 1994, Akari moves to the nearby prefecture of Tochigi due to her parents' jobs. The two keep in contact by writing letters but eventually begin to drift apart. When Takaki learns that his family will be moving to Kagoshima on the other side of the country the following year in 1995, he decides to personally go see Akari one last time since they will be too far apart to see and visit each other once he moves. He also writes a letter for Akari to confess his feelings for her. However, Takaki loses the letter during the journey and a severe snowstorm delays his train for several hours. When the two finally meet late that night and share their first kiss, Takaki realizes they will never be together. They find a shed to spend the night in due to the severe snowstorm and fall asleep after talking late into the night. Takaki departs from the train station the next morning and the two promise to continue writing to each other. As the train rolls away, Takaki decides that the loss of his letter is not important anymore after the kiss while Akari silently looks at her own letter addressed to Takaki which she decided not to give him.",
                "https://static.wikia.nocookie.net/makotoshinkai/images/7/79/5_Centimeters_Per_Second_poster.jpg"));

        movies.add(new Movies("m9",
                "Stand by Me Doraemon",
                "Ryūichi Yagi, Takashi Yamazaki",
                "Animation, Science Fiction, Comedy, Drama",
                "8 August 2014",
                "1h 34min",
                "Nobita Nobi is a Fifth grader who constantly gets failing grades in his subjects due to his laziness and is always bullied by his classmates Suneo Honekawa and Takeshi \"Gian\" Goda. His great-great grandson from the 22nd century, Sewashi, who watches him every day, travels to Nobita's timeline while bringing along his robotic cat Doraemon. Sewashi reveals that if Nobita keeps up his act, he will have a disastrous future: he will marry Gian's sister Jaiko, have his private company burned down, and will be left with a great debt. To circumvent this, he orders Doraemon to help Nobita, modifying Doraemon's nose to prevent him from returning to the future unless Nobita gains a better future.\n" +
                        "\n" +
                        "Being reluctant until the threat, Doraemon introduces his gadgets to help Nobita which helps him immensely. Though Doraemon warns Nobita not to be too dependent on his gadgets, Nobita asks Doraemon to help him woo his crush Shizuka \"Sue\" Minamoto whom Doraemon reveals is the one Nobita will marry if his future is corrected. However, all his efforts end up making Shizuka become closer to ace student, Hidetoshi Dekisugi. Nobita's attempt to be equal with Dekisugi by studying harder is futile, and he decides to let go of Shizuka to make her happier. He does this by flipping Shizuka's skirt to reveal her underwear (but not looking at it), resulting in Shizuka slapping him and running away in tears. After a while, Shizuka starts worrying about Nobita. She overhears Gian and Suneo's conversation about Nobita's self-esteem getting crushed by Sensei for recently failing another test, causing her to believe he is planning to commit suicide, Shizuka arrives at the Nobi residence and resists Nobita's people-repelling potion to help him, which Doraemon reveals is the first step in Nobita and Shizuka's growing relationship to eventually becoming a couple.\n" +
                        "\n" +
                        "After seeing his older self rejecting Shizuka's invitation to a mountain climbing, Nobita disguises himself as his older self to help Shizuka, who becomes separated from her group during a heavy blizzard. His efforts to help Shizuka do more harm to himself, but this makes Shizuka feel that she has to accompany Nobita, saying \"Yes\" before collapsing from cold she contracted from her earlier conversation with Nobita. Forcing himself to remember the moment, the two are rescued by Nobita's older self, who recalled the memory. Nobita learns from his older self that Shizuka was answering to latter's proposition to marry her. It means that Shizuka will indeed marry Nobita. After hearing that Shizuka's father has also accepted Nobita as his daughter's spouse, Nobita and Doraemon return to the present timeline. Nobita visits Shizuka declaring that he will make her happy whatever it takes.\n" +
                        "\n" +
                        "As Nobita's future has been changed for the better, Doraemon's programming commands him to return to the future in 48 hours. Noticing that Doraemon has a hard time leaving due to his worry for Nobita, Nobita confronts and has a brutal fight with Gian to prove that he is able to defend himself without Doraemon. Seeing that Nobita refuses to give up, Gian forfeits as Doraemon tearfully takes Nobita home before leaving in peace the next day. During April Fools, Nobita is tricked by Gian into believing that Doraemon has returned. In anger, he drinks a solution Doraemon gave to him which the opposite of everything the consumer says comes true. Finishing his retribution against Suneo (who was chased by a dog trying to bite him) and Gian (who was being dragged away by his mother who was preparing to punish him), Nobita goes back home while lamenting that Doraemon will never return. To his surprise, Doraemon suddenly returns and tells Nobita that he has gotten permission to stay with him because Nobita said that Doraemon would never return, still with the effects of the potion, and it became a truth. They both hug and cry in happiness.",
                "https://3.bp.blogspot.com/-aylJJ7Opi4Y/W_QTWHItWkI/AAAAAAAABLc/dKZQgF8WYgkLEb1Yj50dKFXB-54E0kzCwCHMYCw/s800/channel-studio-studio-design-dan-karya-siswa-download.jpg"));

        movies.add(new Movies("m10",
                "Spirited Away",
                "Hayao Miyazaki",
                "Animation, Fantasy",
                "20 July 2001",
                "2h 5min",
                "Ten-year-old Chihiro and her parents are traveling to their new home. Her father, a man who loves to take shortcuts, ends up in front of a tunnel leading to what appears to be an abandoned village, which Chihiro's father insists on exploring despite his daughter's misgivings. While exploring, Chihiro finds an exquisite bathhouse and meets a boy named Haku, who warns her to return across the riverbed before sunset. However, Chihiro discovers too late that her parents have transformed into pigs, and she is unable to cross the now-flooded river.\n" +
                        "\n" +
                        "Haku finds Chihiro and advises her to ask for a job from the bathhouse's boiler-man, Kamaji. Kamaji asks Lin, a bathhouse worker, to send Chihiro to Yubaba, the witch who runs the bathhouse. Yubaba tries to frighten Chihiro away, but Chihiro persists, and Yubaba hires her. Yubaba takes away the second kanji of her name, Chihiro (千尋), renaming her Sen (千). Haku later warns her that if she forgets her name like he has forgotten his, she will not be able to leave the spirit world.\n" +
                        "\n" +
                        "Sen is treated poorly by the other bathhouse workers; only Kamaji and Lin show sympathy for her. While working, she invites a silent creature named No-Face inside, believing him to be a customer. A \"stink spirit\" arrives as Sen's first customer, and she discovers he is the spirit of a polluted river. In gratitude for cleaning him, he gives Sen a magic emetic dumpling. Meanwhile, No-Face, imitating the gold left behind by the stink spirit, tempts a worker with gold and then swallows him. He demands food and begins tipping expensively. He swallows two more workers when they interfere with his conversation with Sen.\n" +
                        "\n" +
                        "Sen sees paper Shikigami attacking a Japanese dragon and recognizes the dragon as Haku. When a grievously injured Haku crashes into Yubaba's penthouse, Sen follows him upstairs. A shikigami that stowed away on her back shapeshifts into Zeniba, Yubaba's twin sister. She transforms Yubaba's son, Boh, into a mouse and mutates Yubaba's harpy into a tiny bird. As a decoy she turns Yubaba's three tsurube-otoshi into Boh. Zeniba tells Sen that Haku has stolen a magic golden seal from her, and warns Sen that it carries a deadly curse. Haku destroys the shikigami, eliminating Zeniba's manifestation. He falls into the boiler room with Sen, Boh, and the harpy, where Sen feeds him part of the dumpling, causing him to vomit both the seal and a black slug, which Sen crushes with her foot.\n" +
                        "\n" +
                        "With Haku unconscious, Sen resolves to return the seal and apologize to Zeniba. Sen confronts No-Face, who is now massive, and feeds him the rest of the dumpling. No-Face follows Sen out of the bathhouse, regurgitating everything and everyone he has eaten. Sen, No-Face, Boh, and the harpy travel by train to meet Zeniba. Yubaba orders that Sen's parents be slaughtered, but Haku reveals that Boh is missing and offers to retrieve him if Yubaba releases Sen and her parents.\n" +
                        "\n" +
                        "Zeniba reveals that Sen's love for Haku broke her curse and that Yubaba used the black slug to take control over Haku. Haku appears at Zeniba's home in his dragon form and flies Sen, Boh, and the harpy to the bathhouse. No-Face decides to remain with Zeniba. In mid-flight, Sen recalls falling years ago into the Kohaku River and being washed safely ashore, correctly guessing Haku's real identity as the spirit of the river and freeing him from Yubaba's spell in the process.\n" +
                        "\n" +
                        "When they arrive at the bathhouse, Yubaba forces Sen to identify her parents from among a group of pigs in order to break their curse. After Sen answers correctly that none of the pigs are her parents, she is free to go. Haku takes her to the now-dry riverbed and vows to meet her again. Chihiro returns through the tunnel with her parents, who do not remember anything after eating at the restaurant stall. Chihiro looks back at the tunnel, unsure if her adventure really happened. When they reach their car, they find it covered in dust and leaves, but drive off toward their new home",
                "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"));
        return movies;
    }

    public static ArrayList<TvShows> generateDummyTvShows() {
        ArrayList<TvShows> tvshows = new ArrayList<>();

        tvshows.add(new TvShows("tv1",
                "Death Note",
                "Toshio Nakatani, Manabu Tamura, Masao Maruyama",
                "Animation, Mystery, Psychological Thriller",
                "3 October 2006",
                "37",
                "In Tokyo, a disaffected high-school student named Light Yagami finds the \"Death Note\", a mysterious black notebook which can kill anyone as long as the user knows both the target's name and face. Initially terrified of its god-like power, Light considers the possibilities of the Death Note's abilities and kills high-profile Japanese criminals, then targeting international criminals. Five days after discovering the notebook, Light is visited by Ryuk, a \"Shinigami\" and the Death Note's previous owner. Ryuk, invisible to anyone who has not touched the notebook, reveals that he dropped the notebook into the human world out of boredom and is amused by Light's actions.[5]\n" +
                        "\n" +
                        "As criminals around the world die from inexplicable accidents and heart attacks, the global media suggest that a single mastermind is responsible for the mysterious murders and name him \"Kira\" (キラ, the Japanese transliteration of the English word \"killer\"). Hoping to apprehend Kira, Interpol requests the assistance of an enigmatic consulting detective, known as L, to assist their investigation. Deducing that Kira is based in Japan, L tricks Light into revealing that he is in the Kanto region of Japan by manipulating him to kill a decoy. Furious, Light vows to kill L, whom he views as obstructing his plans. L deduces that Kira has inside knowledge of the Japanese police investigation, being led by Light's father, Soichiro Yagami. Under the suspicion that \"Kira\" could have family ties with members of the \"Kira\" investigation, L assigns a team of FBI agents to monitor the families of those connected with the investigation and L learns enough to designate Light as the prime suspect. Around this time, Light graduates from high school to college. L recruits Light into the Kira Task Force, with each trying to get the other to reveal crucial information.\n" +
                        "\n" +
                        "Actress-model Misa Amane, having obtained a second Death Note from a Shinigami named Rem, makes a deal with Rem for Shinigami eyes, which allow her to kill knowing only the face, at the cost of half her lifespan. Seeking to have Light become her boyfriend, Misa uncovers Light's identity as the original Kira, but Light has another motive: he intends to use Misa's Shinigami eyes to discern L's true name. L deduces that Misa is likely the second Kira and detains her. Rem threatens to kill Light if he does not find a way to save Misa. Light arranges a scheme in which he and Misa temporarily lose their memories of the Death Note, and has Rem pass the Death Note to a less morally driven individual, Kyosuke Higuchi of the Yotsuba Group. With memories of the Death Note erased, Light joins the investigation and, together with L, deduce Higuchi's identity and arrest him. Light regains his memories and uses the Death Note to kill Higuchi, regaining possession of the book. After restoring Misa's memories, Light instructs her to begin killing as Kira, causing L to cast suspicion on Misa. With Light insinuating the investigation would lead to Misa's capture and execution, Rem realizes Light's plan all along was to have her sacrifice herself to kill L, as a Shinigami may not kill others to prevent a human's death. After Rem kills L, she disintegrates and Light obtains her Death Note. The task force does not announce L's death and agrees to have Light operate as the new L. With Light working as both L and Kira, the investigation stalls but crime rates continue to drop as he no longer has threat of capture.\n" +
                        "\n" +
                        "Four years later, cults have arisen which adore Kira. Two young men, raised as potential successors to L, are revealed: Near and Mello. Aware that L is dead, they consider Light, the current L, as a prime suspect. Mello, with Mafia assistance, kidnaps Light's sister, resulting in his father's death during a rescue mission. As suspicion falls again on Misa, Light passes Misa's Death Note to a fervent supporter of Kira, Teru Mikami. He also appoints newscaster Kiyomi Takada as Kira's public spokesperson. Realizing that Takada is connected to Kira, Mello kidnaps her. Takada kills Mello but is killed by Light. Near deduces Mikami's connection to Kira and arranges a meeting between Light and the current Kira Task Force members. Light tries to have Mikami kill Near as well as all the task force members, but Mikami's Death Note fails to work, having been replaced with a decoy. Perusing the names Mikami had written down, only Light's is missing, which proves Light is Kira. Light is grievously wounded in a scuffle and begs Ryuk to write the names of everyone present. Ryuk instead writes down Light's name in his Death Note, as Light declares himself as god of the new world before dying.\n" +
                        "\n" +
                        "Three years later, Near, now functioning as the new L, receives word that a new Kira has appeared. Hearing that the new Kira is randomly killing people, Near concludes that the new Kira is an attention-seeker and denounces the new Kira as \"boring\" and not worth catching. A Shinigami named Midora approaches Ryuk and gives him an apple from the human realm, in a bet to see if a random human could become the new Kira, but Midora loses the bet when the human writes his own name in the Death Note after hearing Near's announcement. Ryuk tells Midora that no human would ever surpass Light as the new Kira.",
                "https://m.media-amazon.com/images/I/716ASj7z2GL._AC_SL1000_.jpg"));

        tvshows.add(new TvShows("tv2",
                "Assassination Classroom",
                "Seiji Kishi",
                "Animation, Action, Science Fiction Comedy",
                "9 January 2015",
                "47 + 1 OVA",
                "Earth is left in jeopardy after an immensely powerful tentacled creature suddenly appears and destroys 75% of the moon, leaving it permanently in the shape of a crescent. The organism claims that within a year he will destroy the planet next, but offers mankind a chance to avert this fate. In class 3-E, the End Class of Kunugigaoka Junior High School, he starts working as a homeroom teacher where he teaches his students regular subjects, as well as the ways of assassination. The Japanese government promises a reward of ¥10 billion (i.e. US$100 million) to whoever among the students succeeds in killing the organism, whom they have named \"Koro-sensei\" (殺せんせー, Korosensē, a pun on korosenai (殺せない, unkillable) and sensei (先生, teacher)). However, this proves to be a highly unachievable task, as not only does he have several superpowers at his disposal, including accelerated regeneration, visual cloning, an invincible form, and the ability to move and fly at Mach 20, but he is also the best teacher they could ask for, helping them to improve their grades, individual skills, and prospects for the future.\n" +
                        "\n" +
                        "As the series goes on, the situation gets even more complicated as other assassins come after Koro-sensei's life, some coveting the reward, others for personal reasons. The students eventually learn the secrets involving him, the Moon's destruction, and his ties with their previous homeroom teacher including the true reason why he must be killed before the end of the school year. The series is narrated by Nagisa Shiota, one of the students in the class whose main strategy in killing Koro-sensei is making a list of all his weaknesses over time. At first, Nagisa appears to be one of the weaker members of Class 3-E, but he later emerges as one of the most skillful assassins in the class.\n",
                "https://m.media-amazon.com/images/M/MV5BYzI0OWJlMjItYmE1NS00YzE2LWExNDAtMDM3MDA5MzM5NmExXkEyXkFqcGdeQXVyNzA5MDUyODA@._V1_.jpg"));

        tvshows.add(new TvShows("tv3",
                "My Hero Academia",
                "Kenji Nagasaki, Tomo Ōkubo, Masahiro Mukai",
                "Animation, Adventure, Superheroes",
                "3 April 2016",
                "96",
                "The story of My Hero Academia is set in a world where currently most of the human population has gained the ability to develop superpowers called \"Quirks\" (個性, Kosei), which occur in children within the age of four: it is estimated that around 80% of the world population has a Quirk. There are infinite types of Quirks, and it is extremely unlikely to find two people who have the exact same power, unless they are closely related. These particular abilities have allowed the development of a new category of people: Heroes, who face the evil-voted individuals who use the Quirks for selfish and criminal purposes, commonly known as Villains. In addition, Heroes who choose to exercise heroism at work level are recognized as Pro Heroes.\n" +
                        "\n" +
                        "The series focuses on Izuku Midoriya, a young man who dreams of becoming a Hero despite being bullied by his violent childhood friend Katsuki Bakugo for lacking a Quirk. Both youths idolize one of the world's greatest heroes All Might, who they both met with Izuku being one of few to know of an critical injury All Might has been concealing from the public eye to maintain morale. All Might also reveals the nature of his Quirk \"One For All\" and passes it down to Izuku to succeed him after seeing the youth's determination in the face of danger. As Izuku begins his path to becoming a hero in attending U.A. High School (雄英高校, Yūei Kōkō) alongside Bakugo and the friends they make in Class 1-A, a nemesis to the \"One For All\" users named All For One conditions his apprentice Tomura Shigaraki to destroy the current society and its heroes.",
                "https://images-na.ssl-images-amazon.com/images/I/91kjVOEopVL._AC_SL1500_.jpg"));
        tvshows.add(new TvShows("tv4",
                "Black Clover",
                "Tatsuya Yoshihara, Ayataka Tanemura",
                "Animation, Adventure, Fantasy",
                "16 February 2015",
                "28",
                "The series focuses on Asta, a young orphan who was raised from birth after being abandoned at the doorstep of an orphanage in Hage village along with his fellow orphan, Yuno. While everyone is born with the ability to utilize Mana in the form of Magical Power (魔力, Maryoku), Asta is an exception (due to the anti magic demon living inside him). He tries to gain magical power through physical training. Conversely, Yuno was born as a prodigy with immense magical power and the talent to control wind magic. Motivated by a desire to become the next Wizard King, an authority figure second to the king of Clover Kingdom, the two youths developed a friendly rivalry. Yuno obtains a legendary four-leaf grimoire held by the kingdom's first Wizard King. Asta, despite his lack of magic, obtained the mysterious five-leaf grimoire (which cannot be clearly identified by others since it is worn out), which contains mysterious elf swords and rare anti-magic. Afterward, he and Yuno each join a Magic Knight squad as the first step to fulfill their ambitions. Throughout the story Asta and Yuno embark on various adventures, as they make a name for themselves throughout the Clover Kingdom.",
                "https://i.pinimg.com/originals/7e/b1/cc/7eb1cccad75f6cd8559551b2d0902c47.png"));

        tvshows.add(new TvShows("tv5",
                "Your Lie in April",
                "Kyōhei Ishiguro",
                "Animation, Musical, Drama",
                "9 October 2014",
                "22",
                "Piano prodigy Kōsei Arima dominates various music competitions and becomes famous among child musicians. When his mother Saki dies suddenly, he has a mental breakdown while performing at a piano recital; this results in him no longer being able to hear the sound of his piano even though his hearing is otherwise perfectly fine.\n" +
                        "\n" +
                        "Two years later, Kōsei has not touched the piano and views the world in monochrome, without any flair or color. He resigns himself to living out his life with his good friends Tsubaki and Watari, until one day, a girl changes everything. Kaori Miyazono, an audacious, free-spirited, fourteen-year-old violinist whose playing style reflects her manic personality. She helps Kōsei return to the music world and shows him that it should be free and mold-breaking, unlike the structured and rigid style Kōsei was used to. As she continues to uplift him, he quickly realizes that he loves her, although she already likes Watari.\n" +
                        "\n" +
                        "Later, while performing together, Kaori suddenly collapses after a moving performance and is hospitalised. At first Kaori says that she is anaemic and just needs some routine testing, but this is revealed to be a lie. Kaori is discharged and back to her happy self, inviting Kōsei to play at a Gala with her. However, Kaori fails to show up on the day of the Gala, and as her health deteriorates, she becomes dejected. Kōsei plays a duet with Nagi Aiza, in the hope of motivating her. After listening to it, Kaori opts for a risky surgery that may kill her if it fails, just so that she can play with him one more time. While playing in the finals of the Eastern Japan Piano Competition, Kōsei sees Kaori's spirit accompanying him and eventually realizes that she has died during the surgery.\n" +
                        "\n" +
                        "A letter written by Kaori was given to Kōsei by her parents at her funeral. The letter reveals that she was aware that she was about to die, so she became more free-spirited, both as a person and in her music, in order to not take her regrets to Heaven. She also reveals that she had been in love with Kōsei since she was five, and was inspired to play the violin so that she could one day play with him. Her supposed feelings towards Watari was a lie, fabricated in order to get closer to Kōsei without hurting Tsubaki, who also has limerent feelings towards Kōsei. After finding this out, Tsubaki confronts Kōsei and tells him that she will be by his side for the rest of her life. Kaori also leaves behind a picture of her as a child coming back from the concert that inspired her, with Kōsei in the background walking back home. Kōsei later frames this picture.",
                "https://cdn.myanimelist.net/images/anime/3/67177.jpg"));

        tvshows.add(new TvShows("tv6",
                "Fullmetal Alchemist",
                "Seiji Mizushima",
                "Animation, Adventure, Dark Fantasy",
                "12 July 2001",
                "51",
                "Edward and Alphonse Elric live in Resembool with their mother Trisha and father Van Hohenheim, the latter having left without a reason. Trisha soon dies from an illness. After finishing their alchemy training under Izumi Curtis, the Elrics attempt to bring their mother back with alchemy. The transmutation backfires, and Edward loses his left leg while Alphonse loses his body. Edward sacrifices his right arm to retrieve Alphonse's soul, binding it to a suit of armor. Edward is invited by Roy Mustang to become a State Alchemist (to research a way to restore their bodies) and undergoes a painful medical procedure which grants him prosthetic automail limbs. Edward becomes a State Alchemist, with the title of Fullmetal Alchemist. The Elrics spend the next three years searching for the mythical Philosopher's Stone to achieve their goals.\n" +
                        "\n" +
                        "The Elrics are eventually attacked by an Ishbalan serial killer known as Scar, who targets State Alchemists in revenge for his people's genocide in the Ishbalan civil war. Returning to Resembool to have Edward's limbs repaired by their childhood friend and mechanic, Winry Rockbell, the Elrics meet Dr. Marcoh, who provides them with clues to learn that a Philosopher's Stone is created from human souls. They investigate a laboratory in which the Stones were created, but are hindered by the Homunculi. The Elrics decide to visit Izumi, hoping to improve their alchemy. Mustang's friend Maes Hughes continues the Elrics' research and finds out about a government conspiracy, but is killed by the homunculus Envy. The Elrics learn from Izumi that she attempted to use alchemy to revive her stillborn child. Alphonse is captured by the homunculus Greed, but is rescued by Amestris' leader King Bradley. Bradley is revealed to be the homunculus Wrath, and brings the captured Greed to the Homunculi's creator, Father. When Greed refuses to rejoin his fellow Homunculi, he is reabsorbed by Father.\n" +
                        "\n" +
                        "After meeting the Xingese prince Lin Yao, who seeks a Philosopher's Stone to cement his position as heir to his country's throne, the Elrics return to Central City, where they learn of Hughes's murder. Lieutenant Maria Ross is framed for Hughes' murder, so Mustang fakes Ross's death and smuggles her out of the country. In encounters with the Homunculi, Mustang kills Lust. Lin captures Gluttony, who swallows Lin, Edward, and Envy into his void-like stomach. They escape from Gluttony's stomach after he takes Alphonse to meet Father, who makes Lin the vessel of Greed. Mustang tries to expose Bradley to the government, but finds that the higher officials are complicit in Father's plans. The Elrics and Mustang are released, but warned not to oppose Father, who seeks to use them as \"human sacrifices\". Meanwhile, Scar heads north with the Xingese princess May Chang, fired corrupt official Yoki, and kidnapped Dr. Marcoh.\n" +
                        "\n" +
                        "The Elrics head north as well, and reach Fort Briggs, commanded by General Olivier Armstrong. They confront the homunculus Sloth and learn that Father founded Amestris to amass enough population to create a massive Philosopher's Stone. With it, he can achieve godhood by absorbing the being beyond the Gate of Truth on the ‘Promised Day’. Forced to work with Solf Kimblee, a murderous former State Alchemist and ally of the Homunculi, the Elrics turn on him and split up, joined by a reformed Scar, his group, Kimblee's chimera subordinates, and later Lin/Greed. Hohenheim reveals that he was made an immortal when Father arranged the fall of Cselkcess four centuries ago, and had been working since then to stop Father.\n" +
                        "\n" +
                        "The Promised Day arrives, with Father planning to use an eclipse and ‘human sacrifices’ in order to trigger the transmutation. The Elrics and their comrades battle Father's minions, with Kimblee and almost all of the Homunculi dying. However, Father manages to activate the nationwide transmutation circle, and absorbs the superior being. Hohenheim and Scar activate countermeasures, draining much of Father's absorbed souls, rendering him unstable. The Elrics and their comrades face Father in a final battle, in which Greed is killed by Father. Alphonse, his armor almost destroyed, sacrifices his soul to restore Edward's right arm. Edward defeats Father, who is dragged into the Gate of Truth, from which he was created. Edward sacrifices his ability to perform alchemy to fully restore Alphonse, while Lin receives a Philosopher's Stone. Hohenheim goes to visit Trisha's grave, where he dies peacefully.\n" +
                        "\n" +
                        "The Elrics return home, but separate two years later to research alchemy further. Years later, Edward and Winry have married and have two children.",
                "https://i.pinimg.com/originals/26/4e/c9/264ec9d43fb4c2c4fbc0a976b42cb05a.jpg"));
        tvshows.add(new TvShows("tv7",
                "Steins;Gate",
                "Hiroshi Hamasaki",
                "Animation, Science Fiction, Psychological thriller",
                "6 April 2011",
                "24 + 1 OVA",
                "Steins;Gate is an adaptation of the visual novel of the same name. It is set in 2010 in Akihabara, Tokyo, and follows Rintaro Okabe, a self-proclaimed \"mad scientist\", who runs the \"Future Gadget Laboratory\" in an apartment together with his friends Mayuri Shiina and Itaru \"Daru\" Hashida. While attending a conference about time travel, Okabe finds the dead body of Kurisu Makise, a neuroscience researcher; he sends a text message about it to Daru, and later discovers that Kurisu is alive, and that the message arrived before he sent it. The laboratory members learn that the cell phone–operated microwave oven they are developing can send text messages back in time; they are joined by Kurisu, and investigate it, sending text messages – referred to as \"D-mails\" – to the past to change the present. Kurisu eventually creates a device that can send memories through the microwave oven, effectively allowing the user to time travel.\n" +
                        "\n" +
                        "SERN, a fictional organization based on CERN[4] that is secretly researching time travel, learns of the time machine and sends people to the laboratory to retrieve it, killing Mayuri in the process. Okabe goes back in time multiple times to prevent Mayuri's death, but fails each time. He learns that he needs to undo all the changes their D-mails have caused, and does so until he realizes that undoing the first D-mail would return him to the timeline where Kurisu was found dead. Okabe and Kurisu tell each other about their romantic feelings for one another, after which Kurisu tells Okabe to save Mayuri. Daru hacks into SERN's database, and they delete the record of the D-mail, returning them to the original timeline.\n" +
                        "\n" +
                        "Later, Suzuha Amane, Daru's future daughter, arrives in a time machine to tell Okabe that the only way to prevent a time-travel arms race leading to World War III is to prevent Kurisu's father Nakabachi from killing her and stealing her time travel theories. Suzuha and Okabe travel back in time, but Okabe accidentally kills Kurisu himself. Returning to the present, Okabe receives a message from his future self telling him that to escape the current timeline, he needs to save Kurisu while recreating the vision of the dead Kurisu that his past self saw. Traveling back in time again, he provokes Nakabachi into stabbing him, knocks Kurisu unconscious, and puts her in his pool of blood for his past self to see, causing the timeline to diverge into one where Kurisu lives and World War III does not occur.",
                "https://images-na.ssl-images-amazon.com/images/I/61EObBCnIRL._AC_.jpg"));

        tvshows.add(new TvShows("tv8",
                "Re:Zero − Starting Life in Another World",
                "Masaharu Watanabe",
                "Animation, Adventure, Isekai, Dark Fantasy",
                "4 April 2016",
                "50",
                "Subaru Natsuki is a NEET who is suddenly summoned to a fantasy-like world. Just after arriving, he is killed while trying to help a young half-elf he befriends, Emilia, who is a candidate to become the next ruler of the Kingdom of Lugunica, only to revive some hours in the past. After dying some times, Subaru realizes that he has the power to turn back time after his death. After successfully helping Emilia, Subaru starts living in her house as a butler. Out of gratitude and affection for Emilia, Subaru makes use of his newfound ability to protect her and help on her ambition to be successfully appointed as the next queen, also providing assistance to other friends he makes along the way, while suffering due to the pain inflicted on him every time he dies, and carrying along the memories of everything that happened before his power activates, which is forgotten by everybody except for him.",
                "https://m.media-amazon.com/images/M/MV5BN2NlM2Y5Y2MtYjU5Mi00ZjZiLWFjNjMtZDNiYzJlMjhkOWZiXkEyXkFqcGdeQXVyNjc2NjA5MTU@._V1_.jpg"));

        tvshows.add(new TvShows("tv9",
                "Sword Art Online 1",
                "Tomohiko Itō",
                "Animation, Adventure, Science Fiction",
                "8 July 2012",
                "25",
                "In 2022, a virtual reality massively multiplayer online role-playing game (VRMMORPG) called Sword Art Online (SAO) is released. With the NerveGear, a helmet that stimulates the user's five senses via their brain, players can experience and control their in-game characters with their minds. Both the game and the NerveGear were created by Akihiko Kayaba.\n" +
                        "\n" +
                        "On November 6, 10,000 players log into SAO's mainframe cyberspace for the first time, only to discover that they are unable to log out. Kayaba appears and tells the players that they must beat all 100 floors of Aincrad, a steel castle which is the setting of SAO if they wish to be free. He also states that those who suffer in-game deaths or forcibly remove the NerveGear out-of-game will suffer real-life deaths.\n" +
                        "\n" +
                        "One of the players named Kazuto \"Kirito\" Kirigaya, is one of 1,000 testers in the game's previous closed beta. With the advantage of previous VR gaming experience and a drive to protect other beta testers from discrimination, he isolates himself from the greater groups and plays the game alone, bearing the mantle of \"beater\", a portmanteau of \"beta tester\" and \"cheater\". As the players progress through the game Kirito eventually befriends a young girl named Asuna Yuuki, forming a relationship with and later marrying her in-game. After the duo discover the identity of Kayaba's secret ID, who was playing as the leader of the guild Asuna joined in, they confront and destroy him, freeing themselves and the other players from the game.",
                "https://m.media-amazon.com/images/M/MV5BYjY4MDU2YjMtNzY1MC00ODg1LWIwMzYtMWE5YTA3YTI4ZjMxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"));

        tvshows.add(new TvShows("tv10",
                "Dr. Stone",
                "Shinya Iino",
                "Animation, Post-apocalyptic, Science Fiction",
                "5 July 2019",
                "24",
                "Beginning in April 5738 CE, it's been over 3,700 years since a mysterious flash petrified nearly all human life. A 15-year-old genius named Senku Ishigami is suddenly revived to find himself in a world where all traces of human civilization have been eroded by time. Senku sets up a base-camp and begins to study the petrified humans in order to determine the cause of the event, as well as a cure.\n" +
                        "\n" +
                        "Over the next 6 months, Senku's friend Taiju Oki wakes up and Senku learns their revival was made possible with nitric acid. With this discovery, they develop a compound that will allow them to instantly revive others. They begin by reviving a famous martial artist named Tsukasa Shishiō, and their classmate (and Taiju's crush) Yuzuriha Ogawa, with the goal of rebuilding civilization with a focus on science.\n" +
                        "\n" +
                        "Tsukasa ultimately reveals that he opposes Senku's idea of forming a new scientific civilization, believing the old world was tainted and should not be restored. Instead, he desires to establish a new world order based on power and strength, going so far as to destroy any petrified adults he encounters in order to prevent them from interfering with his goals.\n" +
                        "\n" +
                        "After extorting the formula for the revival compound from Senku, Tsukasa attempts to murder him when he realized that Senku knows how to create weapons that he cannot defend against. Believing he successfully killed Senku, Tsukasa leaves to begin establishing his own faction in the Stone World.\n" +
                        "\n" +
                        "After recovering from his near death experience, Senku discovers a tribe of people already living on the planet and sees this as an opportunity to create his Kingdom of Science. These people are originally hesitant, but eventually learn the benefits that science can bring to their survival. Over time, Senku becomes more trusted by the tribe, eventually being taught of their past – where he discovers that the village was started by his adoptive father, along with five other astronauts, who were unaffected due to being in the International Space Station at the time of the petrification event.\n" +
                        "\n" +
                        "Together with his new allies and friends, Senku's Kingdom of Science engages in a war with Tsukasa's clan, ultimately emerging victorious and affirming themselves as a force to be reckoned with. After the victory they discover that Senku's adopted father had left precious metals which can be used as catalysts to mass produce revival fluid in the nearby island which is now inhabited by a tribe known as the Petrification Kingdom, who possess the device used to petrify the world so long ago.",
                "https://images-na.ssl-images-amazon.com/images/I/81A7VtnvO3L._SL1500_.jpg"));


        return tvshows;
    }
}
